spring:
  application:
    name: disconvery-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org:
      springframework: debug